version: "3"

services:
  nginx:
    image: $REGISTRY/ida/nginx:$VERSION
    ports:
      - 4200:80
    networks:
      - ida-net
  ida-backend:
    image: $REGISTRY/ida/backend-server:$VERSION
    volumes:
      - "../backend-server/src:/build/backend-server/src"
      - "../backend-server/target:/build/backend-server/target"
      - "~/ida-local-logs:/usr/local/tomcat/logs"
    networks:
      - ida-net
  ida-frontend:
    image: $REGISTRY/ida/frontend:$VERSION
    volumes:
      - "../frontend/src:/app/src"
      - "../frontend/public:/app/public"
    stdin_open: true
    networks:
      - ida-net
networks:
  ida-net:
