version: "3"

services:
  nginx:
    image: $REGISTRY/ida/nginx:$VERSION
    ports:
      - 8080:80
      - 80:80
    networks:
      - ida-net
  ida-backend:
    image: $REGISTRY/ida/backend-server:$VERSION
    volumes:
      - "/home/ida_mngr/ida-prod-logs:/usr/local/tomcat/logs"
    environment:
      - FUSEKI_URL=http://fuseki:3030/
      - FUSEKI_USER=admin
      - FUSEKI_PW=$FUSEKI_PW
    networks:
      - ida-net
  fuseki:
    image: $REGISTRY/ida/fuseki-server:$VERSION
    environment:
      - ADMIN_PASSWORD=$FUSEKI_PW
    volumes:
      - fuseki-storage:/fuseki
    networks:
      - ida-net
volumes:
  fuseki-storage:
networks:
  ida-net:
