version: "3"

services:
  ida-backend:
    image: $REGISTRY/ida/backend-server:$VERSION
    volumes:
      - "../backend-server/src:/build/backend-server/src"
      - "../backend-server/target:/build/backend-server/target"
    ports:
      - 8090:8090
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/build/backend-server/src/main/resources/ida-chatbot-dialogflow.json
    networks:
      - ida-net
  ida-frontend:
    image: $REGISTRY/ida/frontend:$VERSION
    volumes:
      - "../frontend/src:/app/src"
      - "../frontend/public:/app/public"
    ports:
      - 3200:3200
    stdin_open: true
    networks:
      - ida-net
networks:
  ida-net:
