version: "3"

services:
  nginx:
    image: $REGISTRY/ida/nginx:$VERSION
    ports:
      - 4200:80
    networks:
      - ida-net
  ida-frontend:
    image: $REGISTRY/ida/frontend:$VERSION
    volumes:
      - "../frontend/src:/app/src"
      - "../frontend/public:/app/public"
    stdin_open: true
    networks:
      - ida-net
  fuseki:
    image: $REGISTRY/ida/fuseki-server:$VERSION
    ports:
      - 3030:3030
    environment:
      - ADMIN_PASSWORD=$FUSEKI_PW
    volumes:
      - fuseki-storage:/fuseki
    networks:
      - ida-net
  pydsmx:
    image: $REGISTRY/ida/pydsmx:$VERSION
    volumes:
      -  "../pydsmx/:/app/"
      - "~/ida-datasets/:/app/datasets"
    environment:
      - FUSEKI_URL=http://fuseki:3030/
      - FUSEKI_USER=admin
      - FUSEKI_PW=$FUSEKI_PW
    networks:
      - ida-net
  ida-backend:
    image: $REGISTRY/ida/backend-server:$VERSION
    volumes:
      - "../backend-server/src:/build/backend-server/src"
      - "../backend-server/target:/build/backend-server/target"
      - "~/ida-local-logs:/build/backend-server/logs"
      - "~/ida-datasets/:/build/backend-server/datasets"
    environment:
      - FUSEKI_URL=http://fuseki:3030/
      - FUSEKI_USER=admin
      - FUSEKI_PW=$FUSEKI_PW
      - DB_PATH=/build/backend-server/datasets/
    networks:
      - ida-net
volumes:
  fuseki-storage:
networks:
  ida-net:
