version: "3"

services:
  nginx:
    image: $REGISTRY/ida/nginx:$VERSION
    ports:
      - 8080:80
    networks:
      - ida-net
  ida-backend:
    image: $REGISTRY/ida/backend-server:$VERSION
    volumes:
      - "../logs:/usr/local/tomcat/logs"
    networks:
      - ida-net
networks:
  ida-net:
