version: "3"

services:
  nginx:
    image: $REGISTRY/ida/nginx:$VERSION
    ports:
      - 4200:80
    networks:
      - ida-net
  ida-backend:
    image: $REGISTRY/ida/backend-server:$VERSION
    volumes:
      - "~/ida-qa-logs:/build/backend-server/logs"
    environment:
      - FUSEKI_URL=http://fuseki:3030/
      - FUSEKI_USER=admin
      - FUSEKI_PW=$FUSEKI_PW
    networks:
      - ida-net
  fuseki:
    image: $REGISTRY/ida/fuseki-server:$VERSION
    environment:
      - ADMIN_PASSWORD=$FUSEKI_PW
    volumes:
      - fuseki-storage:/fuseki
    networks:
      - ida-net
volumes:
  fuseki-storage:
networks:
  ida-net:
