version: "3"

services:
  nginx:
    image: $REGISTRY/ida/nginx:$VERSION
    ports:
      - 4200:80
    networks:
      - ida-net
  ida-backend:
    image: $REGISTRY/ida/backend-server:$VERSION
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/usr/local/ida-chatbot-dialogflow.json
    networks:
      - ida-net
networks:
  ida-net:
