FROM node:10.22.0-stretch

WORKDIR /app
COPY frontend/package.json package.json
COPY frontend/package-lock.json package-lock.json
RUN npm ci

COPY frontend/src src
COPY frontend/public public
COPY frontend/scripts scripts
COPY frontend/envs envs

EXPOSE 4200
CMD npm run start:dev
