FROM node:10.22.0-stretch as builder

WORKDIR /app
COPY frontend/package.json package.json
COPY frontend/package-lock.json package-lock.json
RUN npm ci

COPY frontend/src src
COPY frontend/public public

RUN npm run build


FROM nginx:1.15.8

EXPOSE 80

COPY services/nginx/mime.types /etc/nginx/mime.types
COPY services/nginx/nginx.conf /etc/nginx/nginx.conf


COPY --from=builder /app/build /app
