FROM node:10.22.0-stretch

WORKDIR /app
COPY frontend/package.json package.json
COPY frontend/package-lock.json package-lock.json
RUN npm ci

COPY frontend/src src
COPY frontend/public public
COPY frontend/scripts scripts
COPY frontend/envs envs

EXPOSE 4200
RUN npm i -g serve
RUN npm run start:prod
CMD serve -s build -l 4200
