FROM node:10.22.0-stretch

WORKDIR /app
COPY frontend/package.json package.json
COPY frontend/package-lock.json package-lock.json
RUN npm i

COPY frontend/src src
COPY frontend/public public

EXPOSE 3200
CMD npm start
