FROM python:3.7.2-stretch

WORKDIR /app
COPY pydsmx /app

RUN pip install -r requirements.txt

RUN mkdir -p temp-uploads
RUN mkdir -p datasets

ENTRYPOINT FLASK_APP=/app/app.py flask run --host=0.0.0.0
