FROM python:3.7.2-stretch

WORKDIR /app
COPY pydsmx /app

RUN mkdir -p ./temp-uploads

RUN pip install -r requirements.txt

ENTRYPOINT PYTHONUNBUFFERED=1 FLASK_APP=/app/app.py flask run --host=0.0.0.0
