FROM maven:3.6.3-jdk-11 AS maven_build
WORKDIR /build
COPY backend-server/pom.xml backend-server/pom.xml
COPY backend-server/src backend-server/src

WORKDIR /build/backend-server
COPY --from=maven_build /build/backend-server/src/main/resources/ida-chatbot-dialogflow.json /usr/local/
RUN mvn package

FROM tomcat:8.5.37-jre11
EXPOSE 8080
COPY --from=maven_build /build/backend-server/target/ida-ws.war /usr/local/tomcat/webapps
RUN /usr/local/tomcat/bin/catalina.sh start
