FROM maven:3.6.3-jdk-11 AS MAVEN_BUILD
WORKDIR /build
COPY backend-server/pom.xml backend-server/pom.xml
COPY backend-server/src backend-server/src

WORKDIR /build/backend-server
RUN mvn dependency:go-offline
CMD ["mkdir", "datasets"]
EXPOSE 8080
CMD mvn spring-boot:run -P dev
